steps:
- id: "Read Values"
  name: ubuntu
  entrypoint: bash
  args:
    - -c
    - |
      # Read from "/workspace"
      echo "Running FortiDevSec SAST scanner..."
      docker run busybox echo "Hello Dileep"
      #gcr.io/cloud-builders/docker
      #docker run --rm --mount type=bind,source=$(PWD),target=/scan registry.fortidevsec.forticloud.com/fdevsec_sast:latest
