steps:
- name: "gcr.io/cloud-builders/docker"
  entrypoint: bash
  args:
  - '-c'
  - pwd
  - docker run --rm --mount type=bind,source=/workspace,target=/scan registry.fortidevsec.forticloud.com/fdevsec_dast:latest
